### ISSUE TITLE
网页版这个报错了

### ISSUE THREAD

**Issue by windy003** [zhangzhengde0225/HaiChatGPT#5]
![屏幕截图 2024-04-20 194359](https://github.com/zhangzhengde0225/HaiChatGPT/assets/25093437/a2f53389-b470-44ba-91ca-819ef183312b)

**Comment by windy003** [comment]
: webo.query error: HTokenChatBot.query_stream() got an unexpected keyword argument 'user_mgr'. Traceback: Traceback (most recent call last):
  File "/mnt/c/Users/windy/Desktop/HaiChatGPT-stable/HaiChatGPT/src/webui/utils/app_routes.py", line 26, in send_prompt
    webo.query(user, prompt)  # 得到回答保存在用户的chatbot的stream_buffer中
  File "/mnt/c/Users/windy/Desktop/HaiChatGPT-stable/HaiChatGPT/src/webui/utils/web_object.py", line 100, in query
    stream = chatbot.query_stream(
TypeError: HTokenChatBot.query_stream() got an unexpected keyword argument 'user_mgr'

**Comment by windy003** [comment]
而且命令行版没有回复
